# -*- coding: utf-8 -*-
"""
Fonte unica da verdade dos campos dos Books do BooX (v0.1 Lite).
Cada campo: (nome, categoria, tipo, opcoes_ou_dica)
categoria: OBR (obrigatorio) | REC (recomendado) | OPC (opcional)
tipo: texto | lista | int | num | data | bool
Alimenta os templates Excel e a analise de suficiencia.
"""

ENUM = {
    "nucleo": ["U","B","MC","S","P","C","CG"],
    "freq_proc": ["continuo","diario","semanal","mensal","trimestral","semestral","anual","por_evento"],
    "severidade": ["critico","alto","medio","baixo"],
    "status_apont": ["aberto","em_tratamento","vencido","fechado"],
    "origem": ["controles_internos","auditoria","compliance","gestao","regulador"],
    "recorrencia": ["primeira","reincidente"],
    "natureza": ["preventivo","detectivo","corretivo"],
    "mecanismo": ["manual","semi","automatico"],
    "freq_ctrl": ["continuo","diario","semanal","mensal","trimestral","semestral","anual","por_evento","sob_demanda"],
    "status_val": ["apenas_autoavaliado","validado_documentalmente","validado_amostral","validado_completo"],
    "direcao": ["menor_melhor","maior_melhor"],
    "fonte_ext": ["bacen","cvm","anbima","procon","midia","reclame_aqui","ouvidoria","sac"],
    "status_norma": ["vigente","revogada","futura"],
    "alvo_tipo": ["processo","risco"],
    "tipo_visao": ["produto","processo","e2e","disciplina","area","livre"],
    "operador": ["igual","prefixo","em","descendente_de"],
    "tipo_ctrl": ["icaap","operacional","credito","cobranca","mercado","liquidez","compliance","outro"],
}

BOOKS = {
 "B1_processos": {
   "titulo": "B1 — Processos",
   "desc": "Todos os processos do banco (P0->P4). Eixo estrutural do BooX.",
   "campos": [
     ("id","OBR","texto","ID unico do processo (ex: P.CRE.PF)"),
     ("nome","OBR","texto","Nome do processo"),
     ("nivel","OBR","int","Nivel hierarquico 0 a 4"),
     ("area_responsavel","OBR","texto","Area dona do processo (mapeia ao organizacional canonico)"),
     ("parent_id","REC","texto","ID do processo pai (vazio so para P0)"),
     ("nucleo","REC","lista","nucleo"),
     ("criticidade_bia","REC","int","Criticidade BIA 1 a 5"),
     ("descricao","OPC","texto","O que o processo faz"),
     ("entrada","OPC","texto","Inputs (IPSO)"),
     ("saida","OPC","texto","Outputs (IPSO)"),
     ("data_revisao","OPC","data","Ultima revisao (AAAA-MM-DD)"),
     ("frequencia_execucao","OPC","lista","freq_proc"),
     ("volume_transacional","OPC","num","Volume medio de transacoes"),
   ],
 },
 "B6_riscos": {
   "titulo": "B6 — Riscos (taxonomia)",
   "desc": "Riscos no vocabulario do banco. Mapeiam a um R0 canonico via B_MAP. Mundo INERENTE.",
   "campos": [
     ("id","OBR","texto","ID unico do risco local (ex: RL-07)"),
     ("nome","OBR","texto","Nome local do risco"),
     ("nivel","REC","int","Nivel hierarquico 0 a 4"),
     ("parent_id","REC","texto","ID do risco pai"),
     ("disciplina_id","REC","texto","Disciplina associada (ref. B9)"),
     ("descricao","OPC","texto","Descricao do risco"),
     ("categoria_basileia","OPC","texto","Categoria Basileia"),
   ],
 },
 "B6_vinculo_processo_risco": {
   "titulo": "B6 — Vinculo Processo x Risco",
   "desc": "Cada linha = um par avaliavel = uma bolha no 20-box. Mundo INERENTE.",
   "campos": [
     ("processo_id","OBR","texto","ID do processo (ref. B1)"),
     ("risco_id","OBR","texto","ID do risco (ref. B6)"),
     ("materialidade_inerente","OBR","int","Impacto inerente 1 a 5 (eixo Y)"),
     ("materialidade_declarada_por","REC","texto","Quem declarou (CRO, area)"),
     ("notas","OPC","texto","Observacoes"),
   ],
 },
 "B2_apontamentos": {
   "titulo": "B2 — Apontamentos",
   "desc": "Risco MATERIALIZADO. Afetado, gestor, prazo e criticidade vivem aqui.",
   "campos": [
     ("id","OBR","texto","ID unico do apontamento"),
     ("titulo","OBR","texto","Titulo curto da falha"),
     ("severidade","OBR","lista","severidade"),
     ("status","OBR","lista","status_apont"),
     ("risco_id","OBR","texto","Risco relacionado (ref. B6) — ao menos risco OU processo"),
     ("data_abertura","OBR","data","Data de abertura (AAAA-MM-DD)"),
     ("area_afetada","OBR","texto","Quem sofre o impacto da falha"),
     ("area_gestora","OBR","texto","Quem responde pela correcao"),
     ("processo_id","REC","texto","Processo apontado (ref. B1)"),
     ("origem","REC","lista","origem"),
     ("data_prazo","REC","data","Prazo de remediacao"),
     ("responsavel","REC","texto","Responsavel pela remediacao"),
     ("recorrencia","REC","lista","recorrencia"),
     ("descricao","OPC","texto","Descricao do apontamento"),
     ("controle_id","OPC","texto","Controle que falhou (ref. B5)"),
     ("data_fechamento","OPC","data","Data de fechamento (se status=fechado)"),
     ("plano_acao","OPC","texto","Plano de acao"),
     ("valor_perda","OPC","num","Perda financeira materializada (R$)"),
   ],
 },
 "B5_controles": {
   "titulo": "B5 — Controles (5W2H)",
   "desc": "Controles que mitigam riscos. Eficacia puxa o eixo X (ambiente).",
   "campos": [
     ("id","OBR","texto","ID unico do controle"),
     ("acao","OBR","texto","What: o que o controle faz"),
     ("risco_id","OBR","texto","Why: risco mitigado (ref. B6)"),
     ("eficacia_autoavaliada","OBR","int","Eficacia 1 a 5 (autoavaliacao 1a linha)"),
     ("processo_id","REC","texto","Where: processo onde opera (ref. B1)"),
     ("eficacia_validada","REC","int","Eficacia 1 a 5 (validacao 2a linha)"),
     ("status_validacao","REC","lista","status_val"),
     ("natureza","REC","lista","natureza"),
     ("frequencia","REC","lista","freq_ctrl"),
     ("responsavel","REC","texto","Who: quem executa"),
     ("local","OPC","texto","Where: sistema/comite"),
     ("mecanismo","OPC","lista","mecanismo"),
     ("como","OPC","texto","How: descricao da operacao"),
     ("cobertura_pct","OPC","num","How much: % de operacoes cobertas"),
     ("tipo","OPC","lista","tipo_ctrl"),
     ("data_ultimo_teste","OPC","data","Ultimo teste do controle"),
     ("custo","OPC","num","Custo do controle"),
     ("automatizavel","OPC","bool","Oportunidade de automacao (true/false)"),
   ],
 },
 "B10_indicadores": {
   "titulo": "B10 — Indicadores (KRIs)",
   "desc": "KRIs de risco operacional. Trazem dinamica (tendencia).",
   "campos": [
     ("id","OBR","texto","ID unico do KRI"),
     ("nome","OBR","texto","Nome do indicador"),
     ("direcao","OBR","lista","direcao"),
     ("risco_id","OBR","texto","Risco monitorado (ref. B6) — ao menos risco OU processo"),
     ("limite_amarelo","REC","num","Limiar de alerta amarelo"),
     ("limite_vermelho","REC","num","Limiar critico vermelho"),
     ("processo_id","REC","texto","Processo monitorado (ref. B1)"),
     ("disciplina_id","REC","texto","Disciplina (ref. B9)"),
     ("unidade","REC","texto","Unidade (%, R$, contagem, dias)"),
     ("descricao","OPC","texto","O que mede"),
     ("meta","OPC","num","Meta do indicador"),
     ("responsavel_apuracao","OPC","texto","Quem calcula o KRI"),
     ("fonte_dado","OPC","texto","De onde vem o numero"),
     ("frequencia_apuracao","OPC","lista","freq_ctrl"),
   ],
 },
 "B10_indicador_serie": {
   "titulo": "B10 — Serie temporal dos KRIs",
   "desc": "Valores mensais. Minimo 3 meses para calcular tendencia.",
   "campos": [
     ("indicador_id","OBR","texto","ID do KRI (ref. B10_indicadores)"),
     ("competencia","OBR","texto","Mes de referencia (AAAA-MM)"),
     ("valor","OBR","num","Valor observado"),
   ],
 },
 "B8_externos": {
   "titulo": "B8 — Externos, Ouvidoria e SAC",
   "desc": "Sinais externos publicos + manifestacoes de cliente (Ouvidoria, SAC).",
   "campos": [
     ("id","OBR","texto","ID unico do sinal"),
     ("fonte","OBR","lista","fonte_ext"),
     ("tipo","OBR","texto","Tipo do sinal (depende da fonte)"),
     ("data","OBR","data","Data de referencia (AAAA-MM-DD)"),
     ("risco_id","REC","texto","Risco associado (ref. B6) — risco OU disciplina"),
     ("disciplina_id","REC","texto","Disciplina associada (ref. B9)"),
     ("quantidade","REC","num","Quantidade (ex: nro de procedentes)"),
     ("severidade","REC","int","Severidade 1 a 5 (para midia)"),
     ("descricao","OPC","texto","Descricao do sinal"),
     ("processo_id","OPC","texto","Processo associado (ref. B1)"),
     ("status","OPC","texto","Ex: procedente, improcedente, julgado, em_curso"),
     ("valor_metrica","OPC","num","Valor de metrica continua (ex: nota)"),
     ("valor_anterior","OPC","num","Valor anterior (tendencia)"),
     ("periodo","OPC","texto","Periodo de referencia (ex: 2025-Q4)"),
   ],
 },
 "B4_regulacao": {
   "titulo": "B4 — Regulacao",
   "desc": "Normas externas aplicaveis. Contexto e rastreabilidade na v0.1.",
   "campos": [
     ("id","OBR","texto","ID da norma (ex: RES_CMN_4557)"),
     ("regulador","OBR","texto","Regulador emissor (CMN, BCB, CVM...)"),
     ("numero","OBR","texto","Numero da norma"),
     ("status","OBR","lista","status_norma"),
     ("tipo","REC","texto","lei, res_cmn, res_bcb, circ_bcb, inst_cvm..."),
     ("titulo","REC","texto","Titulo da norma"),
     ("ano","REC","int","Ano de publicacao"),
     ("ementa","OPC","texto","Ementa/resumo"),
     ("url_oficial","OPC","texto","Link para o texto oficial"),
   ],
 },
 "B4_vinculo_norma": {
   "titulo": "B4 — Vinculo de normas",
   "desc": "Liga normas a processos e riscos.",
   "campos": [
     ("norma_id","OBR","texto","Norma (ref. B4)"),
     ("alvo_tipo","OBR","lista","alvo_tipo"),
     ("alvo_id","OBR","texto","ID do processo (B1) ou risco (B6)"),
     ("tipo_vinculo","OPC","texto","primaria, secundaria, informativa"),
     ("notas","OPC","texto","Observacoes"),
   ],
 },
 "B9_disciplinas": {
   "titulo": "B9 — Disciplinas",
   "desc": "Disciplinas de risco transversais. Dimensao de corte.",
   "campos": [
     ("id","OBR","texto","ID unico (ex: DISC_CREDITO)"),
     ("nome","OBR","texto","Nome da disciplina"),
     ("responsavel_2linha","REC","texto","Area de 2a linha que monitora"),
     ("descricao","OPC","texto","Escopo da disciplina"),
     ("categoria_basileia","OPC","texto","Categoria Basileia"),
   ],
 },
 "B7_visoes": {
   "titulo": "B7 — Visoes",
   "desc": "Recortes que o CRO quer enxergar. Configuracao, nao dado.",
   "campos": [
     ("id","OBR","texto","ID unico da visao"),
     ("nome","OBR","texto","Nome legivel"),
     ("tipo","OBR","lista","tipo_visao"),
     ("descricao","OPC","texto","O que mostra e por que"),
     ("owner","OPC","texto","Quem mantem"),
     ("regra_afetacao","OPC","texto","afetada ou gestora (para visao por area)"),
   ],
 },
 "B7_visao_filtros": {
   "titulo": "B7 — Filtros das visoes",
   "desc": "Criterios de filtro de cada visao.",
   "campos": [
     ("visao_id","OBR","texto","Visao (ref. B7_visoes)"),
     ("dimensao","OBR","texto","processo, risco, disciplina, segmento, area..."),
     ("operador","OBR","lista","operador"),
     ("valor","OBR","texto","Valor do filtro (ID ou lista com |)"),
   ],
 },
}
